# from selenium import webdriver
# # driver = webdriver.Chrome("C:/chromedriver/chromedriver.exe")
# # driver.maximize_window()
# # from selenium.webdriver.support.select import Select
# # driver.implicitly_wait(10)
# # driver.get("https://practice.automationtesting.in/")
# driver.execute_script("window.scrollBy(0, 600);")
# time.sleep(5)
# selenium_ruby = driver.find_element_by_class_name("post-160").click()
# reviews = driver.find_element_by_class_name("reviews_tab").click()
# star = driver.find_element_by_css_selector(".star-5").click()
# review = driver.find_element_by_id("comment")
# review.send_keys("Nice book!")
# name = driver.find_element_by_id("author")
# name.send_keys("Olga Rudenk")
# email = driver.find_element_by_id("email")
# email.send_keys("olgusha0418@yandex.ru")
# submit = driver.find_element_by_class_name("submit").click()
# driver.quit()